import Head from 'next/head'
import { useState } from 'react'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {
  AiFillInstagram,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai'
import Image from 'next/image';
import MainImage from '../public/images/MainImage.png';
import Footer from '../pages/components/Footer'




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  ; return (
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Davron Mamatkuov Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white  dark:bg-gray-900" >
        <section className="min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <a href="#" cursor="pointer">
              <h1 className="text-xl font-burtons dark:text-white">DevelopedByDavid</h1>
            </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-xl dark:text-white"

                />
              </li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Skills</a></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Projects</a></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" py-2 text-transparent font-medium text-5xl bg-clip-text bg-gradient-to-r from-cyan-500 to-teal-500">Davron Mamatkuov</h2>
            <h3 className="text-2xl font-burtons py-2 text-slate-700">Freelancer Developer</h3>
            <p className="font-medium leading-8 text-gray-500 dark:text-white">Freelancer providing services for programming and
              design content needs. Join me down below and let&apos;s  get
              cracking!</p>
          </div>
          <div className="flex justify-center text-5xl  gap-16 py-2 dark:text-white">
            <a className="text-gray-500 hover:text-sky-400" cursor="pointer" href="
                https://www.linkedin.com/in/davron-mamatkulov-1139441aa/">
              <AiFillLinkedin />
            </a>
            <a className="text-gray-500 hover:text-sky-400" cursor="pointer" href="https://github.com/david99uz">
              <AiFillGithub />
            </a>
            <a className="text-gray-500 hover:text-sky-400" cursor="pointer" href="https://www.instagram.com/daviduz99/">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" mx-auto relative  rounded-full border-double border-4 border-sky-500 w-80 h-80 mt-20 overflow-hidden justify-center">
            <Image src={MainImage} alt="3dImage" layout='fill' objectFit='cover' />
          </div>
        </section>

        <footer className="mt-10 text-center">
          <Footer />
        </footer>
      </main>


    </div >
  )
}
